Models/Contexto.cs
using Microsoft.EntityFrameworkCore;

namespace CRUD_Ajax.Models
{
    public class Contexto : DbContext
    {
        public Contexto(DbContextOptions<Contexto> opcoes) : base(opcoes) { }

        public DbSet<Pessoa> Pessoas { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CRUD_Ajax.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pessoa.cs
namespace CRUD_Ajax.Models
{
    public class Pessoa
    {
        public int PessoaId { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Profissao { get; set; }

    }
}

Controllers/HomeController.cs
using CRUD_Ajax.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_Ajax.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PessoasController.cs
using CRUD_Ajax.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace CRUD_Ajax.Controllers
{
    public class PessoasController : Controller
    {
        private readonly Contexto _contexto;
        public PessoasController(Contexto contexto) => _contexto = contexto;

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> PegarTodos()
        {
            return Json(await _contexto.Pessoas.ToListAsync());
        }

        [HttpPost]
        public async Task<JsonResult> NovaPessoa(Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                await _contexto.Pessoas.AddAsync(pessoa);
                await _contexto.SaveChangesAsync();
                return Json(pessoa);
            }

            return Json(ModelState);
        }

        [HttpGet]
        public async Task<JsonResult> PegarPessoaPeloId(int pessoaId)
        {
            Pessoa pessoa = await _contexto.Pessoas.FindAsync(pessoaId);
            return Json(pessoa);
        }

        [HttpPost]
        public async Task<JsonResult> AtualizarPessoa(Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                _contexto.Pessoas.Update(pessoa);
                await _contexto.SaveChangesAsync();
                return Json(pessoa);
            }

            return Json(ModelState);
        }

        [HttpPost]
        public async Task<JsonResult> ExcluirPessoa(int pessoaId)
        {
            Pessoa pessoa = await _contexto.Pessoas.FindAsync(pessoaId);

            if (pessoa != null)
            {
                _contexto.Pessoas.Remove(pessoa);
                await _contexto.SaveChangesAsync();
                return Json(true);
            }

            return Json(new
            {
                mensagem = "Pessoa não encontrada"
            });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Pessoas/Index.cshtml
@{
    ViewData["Title"] = "Pessoas Cadastradas";
}

<div class="p-5">
    <div class="border border-light border-3 rounded">
        <div class="container">
            <div class="p-5">
                <div class="row">
                    <div class="col-8">
                        <h6>Pessoas cadastradas</h6>
                    </div>
                    <div class="col-4">
                        <button class="btn btn-sm btn-outline-success novaPessoa">Nova pessoa</button>
                    </div>
                </div>

                <hr />

                <div class="p-5 rounded shadow-sm" id="divTabela"></div>
            </div>
        </div>
    </div>
</div>

<div id="modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title"></h6>
            </div>
            
            <div class="modal-body">
                <input type="hidden" class="form-control form-control-sm pessoaId" />
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" class="form-control form-control-sm nome" />
                    <span class="text-danger erroNome d-none"></span>
                </div>

                <div class="form-group">
                    <label>Idade</label>
                    <input type="number" class="form-control form-control-sm idade" />
                    <span class="text-danger erroIdade d-none">Digite um número</span>
                </div>

                <div class="form-group">
                    <label>Profissão</label>
                    <input type="text" class="form-control form-control-sm profissao" />
                    <span class="text-danger erroProfissao d-none">Digite uma profissão</span>
                </div>
            </div>

            <div class="modal-footer">
                <div class="form-group">
                    <input type="button" value="Salvar" class="btn btn-sm btn-outline-success btnSalvar" />
                    <input type="button" value="Cancelar" class="btn btn-sm btn-light" data-bs-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_Ajax</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pessoas" asp-action="Index">CRUD_Ajax</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUD_Ajax - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>